"""Data models for Ares SOC Investigation Agent."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum, IntEnum
from typing import Any


class PyramidLevel(IntEnum):
    """Levels of the Pyramid of Pain.

    Higher levels are harder for adversaries to change.
    The goal is always to climb toward TTPs.

    Attributes:
        HASH_VALUES: Level 1 - Trivial to change.
        IP_ADDRESSES: Level 2 - Easy to change.
        DOMAIN_NAMES: Level 3 - Simple to change.
        NETWORK_HOST_ARTIFACTS: Level 4 - Annoying to change.
        TOOLS: Level 5 - Challenging to change.
        TTPS: Level 6 - Tough to change (the goal).
    """

    HASH_VALUES = 1
    IP_ADDRESSES = 2
    DOMAIN_NAMES = 3
    NETWORK_HOST_ARTIFACTS = 4
    TOOLS = 5
    TTPS = 6


class QuestionSource(Enum):
    """Source engine that generated a question."""

    MITRE_NAVIGATOR = "mitre"
    PYRAMID_CLIMBER = "pyramid"
    LATERAL_EXPANSION = "lateral"
    INITIAL_TRIAGE = "triage"


class QuestionState(Enum):
    """State of an investigative question."""

    PENDING = "pending"
    EXECUTING = "executing"
    ANSWERED = "answered"
    UNANSWERABLE = "unanswerable"
    SUPERSEDED = "superseded"


class InvestigationStage(Enum):
    """Stages of the investigation workflow."""

    TRIAGE = "triage"  # WHAT is happening
    CAUSATION = "causation"  # WHY it happened
    LATERAL = "lateral"  # What is the SCOPE
    SYNTHESIS = "synthesis"  # Generate report


@dataclass
class Evidence:
    """A piece of evidence discovered during investigation.

    Attributes:
        id: Unique identifier for this evidence.
        type: Type of evidence - one of: ip, domain, hash, process, user,
            file, artifact, tool, technique.
        value: The actual evidence value.
        source: Query or tool that found this evidence.
        timestamp: When this evidence was observed (optional).
        pyramid_level: Classification on Pyramid of Pain scale (1-6).
        mitre_techniques: Associated MITRE ATT&CK technique IDs.
        confidence: Confidence score between 0.0 and 1.0.
        metadata: Additional context about this evidence.
    """

    id: str
    type: str
    value: str
    source: str
    timestamp: datetime | None
    pyramid_level: PyramidLevel
    mitre_techniques: list[str] = field(default_factory=list)
    confidence: float = 0.5
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "type": self.type,
            "value": self.value,
            "source": self.source,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "pyramid_level": self.pyramid_level.value,
            "mitre_techniques": self.mitre_techniques,
            "confidence": self.confidence,
            "metadata": self.metadata,
        }


@dataclass
class TimelineEvent:
    """An event in the investigation timeline.

    Attributes:
        id: Unique identifier for this timeline event.
        timestamp: When this event occurred.
        description: Human-readable description of the event.
        evidence_ids: List of evidence IDs supporting this event.
        mitre_techniques: MITRE ATT&CK technique IDs associated with this event.
        confidence: Confidence score between 0.0 and 1.0.
        source: Source of this event (e.g., "investigation", "alert").
    """

    id: str
    timestamp: datetime
    description: str
    evidence_ids: list[str] = field(default_factory=list)
    mitre_techniques: list[str] = field(default_factory=list)
    confidence: float = 0.5
    source: str = "investigation"

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "timestamp": self.timestamp.isoformat(),
            "description": self.description,
            "evidence_ids": self.evidence_ids,
            "mitre_techniques": self.mitre_techniques,
            "confidence": self.confidence,
            "source": self.source,
        }


@dataclass
class InvestigativeQuestion:
    """A question that drives the investigation forward.

    Generated by the MITRE Navigator and Pyramid Climber engines.

    Attributes:
        id: Unique identifier for this question.
        text: The question text.
        source: Which engine generated this question.
        rationale: Why this question matters.
        target_insight: What we hope to learn from answering this.
        target_technique: MITRE technique this question targets (MITRE-specific).
        technique_chain_from: Technique this follows from (MITRE-specific).
        current_pyramid_level: Starting pyramid level (Pyramid-specific).
        target_pyramid_level: Target pyramid level (Pyramid-specific).
        pyramid_elevation_score: Score 0-1 for elevation potential.
        mitre_coverage_score: Score 0-1 for MITRE coverage value.
        confidence_impact_score: Score 0-1 for confidence improvement potential.
        urgency_score: Score 0-1 for time sensitivity.
        state: Current state of this question.
        created_at: When this question was generated.
        answered_at: When this question was answered.
        generated_from_evidence_ids: Evidence that prompted this question.
        generated_from_question_id: Parent question if part of a chain.
        answer_evidence_ids: Evidence collected while answering.
        answer_summary: Summary of the answer.
    """

    id: str
    text: str
    source: QuestionSource
    rationale: str
    target_insight: str

    target_technique: str | None = None
    technique_chain_from: str | None = None

    current_pyramid_level: int | None = None
    target_pyramid_level: int | None = None

    pyramid_elevation_score: float = 0.0
    mitre_coverage_score: float = 0.0
    confidence_impact_score: float = 0.0
    urgency_score: float = 0.0

    state: QuestionState = QuestionState.PENDING
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    answered_at: datetime | None = None

    generated_from_evidence_ids: list[str] = field(default_factory=list)
    generated_from_question_id: str | None = None

    answer_evidence_ids: list[str] = field(default_factory=list)
    answer_summary: str | None = None

    @property
    def priority_score(self) -> float:
        """
        Composite priority score.

        Weights:
        - Pyramid elevation: 3x (we want TTPs, not IOCs)
        - MITRE coverage: 2x (tactical completeness)
        - Confidence impact: 2x (certainty is valuable)
        - Urgency: 1x (time sensitivity)
        """
        return (
            (self.pyramid_elevation_score * 3.0)
            + (self.mitre_coverage_score * 2.0)
            + (self.confidence_impact_score * 2.0)
            + (self.urgency_score * 1.0)
        )

    def can_parallelize_with(self, other: "InvestigativeQuestion") -> bool:
        """Check if this question can run in parallel with another."""
        # Questions in a reasoning chain should be sequential
        if self.generated_from_question_id == other.id:
            return False
        return other.generated_from_question_id != self.id

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "question": self.text,
            "source": self.source.value,
            "rationale": self.rationale,
            "target_insight": self.target_insight,
            "target_technique": self.target_technique,
            "current_pyramid_level": self.current_pyramid_level,
            "target_pyramid_level": self.target_pyramid_level,
            "priority_score": self.priority_score,
            "state": self.state.value,
        }


@dataclass
class InvestigationState:
    """Mutable state for an investigation.

    This is the central state object that tracks everything
    discovered during the investigation.

    Attributes:
        investigation_id: Unique identifier for this investigation.
        alert: The original alert dictionary that triggered investigation.
        stage: Current investigation stage (triage, causation, lateral, synthesis).
        started_at: When the investigation began.
        evidence: List of all evidence collected.
        timeline: List of timeline events in chronological order.
        questions: List of all investigative questions generated.
        executed_queries: Log of all queries executed.
        identified_techniques: Set of MITRE ATT&CK technique IDs found.
        identified_tactics: Set of MITRE ATT&CK tactic IDs found.
        queried_hosts: Set of hosts that have been investigated.
        queried_users: Set of users that have been investigated.
        queried_data_sources: Set of data sources queried.
        technique_names: Cached mapping of technique IDs to names.
        technique_to_tactic: Cached mapping of techniques to their tactics.
        escalated: Whether investigation was escalated to human analyst.
        escalation_reason: Reason for escalation if applicable.
        attack_synopsis: Summary of the attack for the report.
        recommendations: List of recommended actions.
    """

    investigation_id: str
    alert: dict[str, Any]
    stage: InvestigationStage = InvestigationStage.TRIAGE
    started_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    evidence: list[Evidence] = field(default_factory=list)
    timeline: list[TimelineEvent] = field(default_factory=list)

    questions: list[InvestigativeQuestion] = field(default_factory=list)

    executed_queries: list[dict] = field(default_factory=list)

    identified_techniques: set[str] = field(default_factory=set)
    identified_tactics: set[str] = field(default_factory=set)
    queried_hosts: set[str] = field(default_factory=set)
    queried_users: set[str] = field(default_factory=set)
    queried_data_sources: set[str] = field(default_factory=set)

    technique_names: dict[str, str] = field(default_factory=dict)
    technique_to_tactic: dict[str, str] = field(default_factory=dict)

    escalated: bool = False
    escalation_reason: str | None = None
    attack_synopsis: str | None = None
    recommendations: list[str] = field(default_factory=list)

    @property
    def evidence_count(self) -> int:
        return len(self.evidence)

    @property
    def highest_pyramid_level(self) -> int:
        if not self.evidence:
            return 0
        return max(e.pyramid_level.value for e in self.evidence)

    @property
    def ttp_count(self) -> int:
        return len([e for e in self.evidence if e.pyramid_level == PyramidLevel.TTPS])

    def get_evidence_by_id(self, evidence_id: str) -> Evidence | None:
        for e in self.evidence:
            if e.id == evidence_id:
                return e
        return None

    def get_pending_questions(self) -> list[InvestigativeQuestion]:
        return [q for q in self.questions if q.state == QuestionState.PENDING]

    def get_evidence_for_pyramid_questions(self) -> list[dict]:
        """Get evidence formatted for pyramid climber."""
        return [
            {
                "id": e.id,
                "type": e.type,
                "value": e.value,
                "pyramid_level": e.pyramid_level.value,
            }
            for e in self.evidence
        ]

    def to_summary(self) -> dict:
        return {
            "investigation_id": self.investigation_id,
            "stage": self.stage.value,
            "evidence_count": self.evidence_count,
            "timeline_events": len(self.timeline),
            "questions_pending": len(self.get_pending_questions()),
            "questions_total": len(self.questions),
            "techniques_identified": list(self.identified_techniques),
            "highest_pyramid_level": self.highest_pyramid_level,
            "ttp_count": self.ttp_count,
            "hosts_investigated": list(self.queried_hosts),
            "users_investigated": list(self.queried_users),
        }


# Red Team Models
@dataclass
class Target:
    """Primary target information."""

    ip: str
    hostname: str = ""
    domain: str = ""


@dataclass
class Host:
    """Discovered host information."""

    ip: str
    hostname: str = ""
    os: str = ""
    roles: list[str] = field(default_factory=list)
    services: list[str] = field(default_factory=list)


@dataclass
class User:
    """Discovered user account."""

    username: str
    domain: str = ""
    description: str = ""
    is_admin: bool = False


@dataclass
class Credential:
    """Discovered credential."""

    username: str
    password: str
    domain: str = ""
    source: str = ""  # where it was found
    is_admin: bool = False


@dataclass
class Hash:
    """Discovered password hash."""

    username: str
    hash_value: str
    hash_type: str = "NTLM"
    domain: str = ""
    cracked_password: str = ""


@dataclass
class Share:
    """Discovered SMB share."""

    host: str
    name: str
    permissions: str = ""  # READ, WRITE, READ/WRITE
    comment: str = ""


@dataclass
class RedTeamState:
    """Tracks state for red team operations."""

    operation_id: str
    target: Target
    completed: bool = False
    started_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    stage: InvestigationStage = InvestigationStage.TRIAGE
    report_summary: str = ""

    # Discovery tracking
    hosts: list[Host] = field(default_factory=list)
    users: list[User] = field(default_factory=list)
    credentials: list[Credential] = field(default_factory=list)
    hashes: list[Hash] = field(default_factory=list)
    shares: list[Share] = field(default_factory=list)
    weaknesses: list[str] = field(default_factory=list)

    # Operation tracking
    queried_hosts: set[str] = field(default_factory=set)
    tested_credentials: set[str] = field(default_factory=set)
    timeline: list[TimelineEvent] = field(default_factory=list)
    identified_techniques: set[str] = field(default_factory=set)

    # Success flags
    has_domain_admin: bool = False
    has_golden_ticket: bool = False

    @property
    def host_count(self) -> int:
        """Count of discovered hosts."""
        return len(self.hosts)

    @property
    def credential_count(self) -> int:
        """Count of discovered credentials."""
        return len(self.credentials)

    @property
    def admin_count(self) -> int:
        """Count of admin credentials."""
        return sum(1 for c in self.credentials if c.is_admin)

    def get_credential_key(self, username: str, password: str, domain: str = "") -> str:
        """Generate unique key for credential tracking."""
        return f"{domain}:{username}:{password}".lower()
