"""Data models for Ares SOC Investigation Agent."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, IntEnum
from typing import Any


class PyramidLevel(IntEnum):
    """
    Levels of the Pyramid of Pain.

    Higher levels are harder for adversaries to change.
    The goal is always to climb toward TTPs.
    """

    HASH_VALUES = 1  # Trivial to change
    IP_ADDRESSES = 2  # Easy to change
    DOMAIN_NAMES = 3  # Simple to change
    NETWORK_HOST_ARTIFACTS = 4  # Annoying to change
    TOOLS = 5  # Challenging to change
    TTPS = 6  # Tough to change!


class QuestionSource(Enum):
    """Source engine that generated a question."""

    MITRE_NAVIGATOR = "mitre"
    PYRAMID_CLIMBER = "pyramid"
    LATERAL_EXPANSION = "lateral"
    INITIAL_TRIAGE = "triage"


class QuestionState(Enum):
    """State of an investigative question."""

    PENDING = "pending"
    EXECUTING = "executing"
    ANSWERED = "answered"
    UNANSWERABLE = "unanswerable"
    SUPERSEDED = "superseded"


class InvestigationStage(Enum):
    """Stages of the investigation workflow."""

    TRIAGE = "triage"  # WHAT is happening
    CAUSATION = "causation"  # WHY it happened
    LATERAL = "lateral"  # What is the SCOPE
    SYNTHESIS = "synthesis"  # Generate report


@dataclass
class Evidence:
    """A piece of evidence discovered during investigation."""

    id: str
    type: str  # ip, domain, hash, process, user, file, artifact, tool, technique
    value: str
    source: str  # Query or tool that found this
    timestamp: datetime | None
    pyramid_level: PyramidLevel
    mitre_techniques: list[str] = field(default_factory=list)
    confidence: float = 0.5
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "type": self.type,
            "value": self.value,
            "source": self.source,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "pyramid_level": self.pyramid_level.value,
            "mitre_techniques": self.mitre_techniques,
            "confidence": self.confidence,
            "metadata": self.metadata,
        }


@dataclass
class TimelineEvent:
    """An event in the investigation timeline."""

    id: str
    timestamp: datetime
    description: str
    evidence_ids: list[str] = field(default_factory=list)
    mitre_techniques: list[str] = field(default_factory=list)
    confidence: float = 0.5
    source: str = "investigation"

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "timestamp": self.timestamp.isoformat(),
            "description": self.description,
            "evidence_ids": self.evidence_ids,
            "mitre_techniques": self.mitre_techniques,
            "confidence": self.confidence,
            "source": self.source,
        }


@dataclass
class InvestigativeQuestion:
    """
    A question that drives the investigation forward.

    Generated by the MITRE Navigator and Pyramid Climber engines.
    """

    id: str
    text: str
    source: QuestionSource
    rationale: str
    target_insight: str

    # MITRE-specific
    target_technique: str | None = None
    technique_chain_from: str | None = None

    # Pyramid-specific
    current_pyramid_level: int | None = None
    target_pyramid_level: int | None = None

    # Priority scoring components (0-1 scale)
    pyramid_elevation_score: float = 0.0
    mitre_coverage_score: float = 0.0
    confidence_impact_score: float = 0.0
    urgency_score: float = 0.0

    # State
    state: QuestionState = QuestionState.PENDING
    created_at: datetime = field(default_factory=datetime.utcnow)
    answered_at: datetime | None = None

    # Relationships
    generated_from_evidence_ids: list[str] = field(default_factory=list)
    generated_from_question_id: str | None = None

    # Results
    answer_evidence_ids: list[str] = field(default_factory=list)
    answer_summary: str | None = None

    @property
    def priority_score(self) -> float:
        """
        Composite priority score.

        Weights:
        - Pyramid elevation: 3x (we want TTPs, not IOCs)
        - MITRE coverage: 2x (tactical completeness)
        - Confidence impact: 2x (certainty is valuable)
        - Urgency: 1x (time sensitivity)
        """
        return (
            (self.pyramid_elevation_score * 3.0)
            + (self.mitre_coverage_score * 2.0)
            + (self.confidence_impact_score * 2.0)
            + (self.urgency_score * 1.0)
        )

    def can_parallelize_with(self, other: "InvestigativeQuestion") -> bool:
        """Check if this question can run in parallel with another."""
        # Questions in a reasoning chain should be sequential
        if self.generated_from_question_id == other.id:
            return False
        return other.generated_from_question_id != self.id

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "question": self.text,
            "source": self.source.value,
            "rationale": self.rationale,
            "target_insight": self.target_insight,
            "target_technique": self.target_technique,
            "current_pyramid_level": self.current_pyramid_level,
            "target_pyramid_level": self.target_pyramid_level,
            "priority_score": self.priority_score,
            "state": self.state.value,
        }


@dataclass
class InvestigationState:
    """
    Mutable state for an investigation.

    This is the central state object that tracks everything
    discovered during the investigation.
    """

    investigation_id: str
    alert: dict[str, Any]
    stage: InvestigationStage = InvestigationStage.TRIAGE
    started_at: datetime = field(default_factory=datetime.utcnow)

    # Evidence and timeline
    evidence: list[Evidence] = field(default_factory=list)
    timeline: list[TimelineEvent] = field(default_factory=list)

    # Question tracking
    questions: list[InvestigativeQuestion] = field(default_factory=list)

    # Query tracking
    executed_queries: list[dict] = field(default_factory=list)

    # Coverage tracking
    identified_techniques: set[str] = field(default_factory=set)
    identified_tactics: set[str] = field(default_factory=set)
    queried_hosts: set[str] = field(default_factory=set)
    queried_users: set[str] = field(default_factory=set)
    queried_data_sources: set[str] = field(default_factory=set)

    # MITRE lookups (cached for report)
    technique_names: dict[str, str] = field(default_factory=dict)
    technique_to_tactic: dict[str, str] = field(default_factory=dict)

    # Completion
    escalated: bool = False
    escalation_reason: str | None = None
    attack_synopsis: str | None = None
    recommendations: list[str] = field(default_factory=list)

    @property
    def evidence_count(self) -> int:
        return len(self.evidence)

    @property
    def highest_pyramid_level(self) -> int:
        if not self.evidence:
            return 0
        return max(e.pyramid_level.value for e in self.evidence)

    @property
    def ttp_count(self) -> int:
        return len([e for e in self.evidence if e.pyramid_level == PyramidLevel.TTPS])

    def get_evidence_by_id(self, evidence_id: str) -> Evidence | None:
        for e in self.evidence:
            if e.id == evidence_id:
                return e
        return None

    def get_pending_questions(self) -> list[InvestigativeQuestion]:
        return [q for q in self.questions if q.state == QuestionState.PENDING]

    def get_evidence_for_pyramid_questions(self) -> list[dict]:
        """Get evidence formatted for pyramid climber."""
        return [
            {
                "id": e.id,
                "type": e.type,
                "value": e.value,
                "pyramid_level": e.pyramid_level.value,
            }
            for e in self.evidence
        ]

    def to_summary(self) -> dict:
        return {
            "investigation_id": self.investigation_id,
            "stage": self.stage.value,
            "evidence_count": self.evidence_count,
            "timeline_events": len(self.timeline),
            "questions_pending": len(self.get_pending_questions()),
            "questions_total": len(self.questions),
            "techniques_identified": list(self.identified_techniques),
            "highest_pyramid_level": self.highest_pyramid_level,
            "ttp_count": self.ttp_count,
            "hosts_investigated": list(self.queried_hosts),
            "users_investigated": list(self.queried_users),
        }
